[package]
name = "cube-solver"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
miniz_oxide = "0.8"
cube-core.workspace = true
kewb.workspace = true

[target.'cfg(target_arch = "wasm32")'.dependencies]
getrandom.workspace = true

[dev-dependencies]
cube-vision = { path = "../cube-vision" }
miniz_oxide = "0.8"
